### ISSUE TITLE
Verbeterpunten design 

### ISSUE THREAD

**Issue by Hadil66** [Hadil66/Accessibility#9]
# Verbeterpunten
### De buttons op de banner staan te dicht op elkaar
<img src="https://github.com/user-attachments/assets/6496ebdc-8976-484f-b254-6d7637a687b6" width="500px">

### Het contrast op de banner is laag
<img src="https://github.com/user-attachments/assets/8559a8e8-4e91-4c9b-8446-3e85ee54c39f" width="500px">

### Het contrast is te laag
<img src="https://github.com/user-attachments/assets/450c5035-c06d-4fdd-88ea-e0a1efd793f3" width="500px">

### Cursor is niet zichtbaar
<img src="https://github.com/user-attachments/assets/992c372c-7690-44b2-af98-2980d8bf0bbe" width="500px">

### Het contrast tussen de navbar en achtergrond is niet altijd even hoog, op de scroll omhoog active state ook laag
<img src="https://github.com/user-attachments/assets/8e109467-36bd-44e5-b7c9-f59e0842158d" width="500px">
<img src="https://github.com/user-attachments/assets/bfd280a1-5576-4678-b32a-f83b4a8a48d0" width="500px">

### Het contrast in de footer banner is te laag
<img src="https://github.com/user-attachments/assets/7cccc84e-3d78-4f6c-969d-f06af979f582" width="500px">

### Het contrast in het laatste blok op de users pagina is te laag
<img src="https://github.com/user-attachments/assets/19d53123-90db-4fba-827e-2202afab914b" width="500px">

### Het linkje 'terug' lijkt op een list item
_in het dropdownmenu; service & pooling_
<img src="https://github.com/user-attachments/assets/a80c70ba-a392-450d-85c4-947e152ac64f" width="500px">

### Te veel witruimte
<img src="https://github.com/user-attachments/assets/890f903d-9b06-471e-9b72-7fab193d9d86" width="500px">

### Met de focusstate krijg je een button te zien en de afbeelding wordt kleiner
<img src="https://github.com/user-attachments/assets/95dfb3d9-9f9e-4cf9-b122-62abf8606305" width="500px">
<img src="https://github.com/user-attachments/assets/d28719df-c529-432c-b717-d6dcc0be1b96" width="500px">

### Focus niet altijd even goed zichtbaar
<img src="https://github.com/user-attachments/assets/2ecb4d02-3f84-4d1e-a5c8-36c8da87d446" width="500px">

**Comment by Hadil66** [comment]
# Verbeteringen

### De rechterbutton heeft nu een `margin-left` van `2em`
<img src="https://github.com/user-attachments/assets/2f606cc4-e440-4b0e-b7c4-fef5f121d423" width="500px"> 

### Om het contrast te verhogen heb ik een overlay geplaatst op de image. `linear-gradient(to right, #00453e 0%, rgba(0, 87, 79, 0.15) 90.26%, rgba(0, 88, 80, 0) 100%);` Dit is hetzelfde gradient die op andere plaatsten op de site gebruikt wordt. De stijl blijft zo consistent. Het contrast tussen de navbar en achtergrond is nu ook veel groter.

<img src="https://github.com/user-attachments/assets/086266cb-6084-4697-b151-aa3b71f9869e" width="500px"> 

### Brandcolour 2 heeft een hoger contrast, dus alle tekst met brandcolour 3 zal ik naar brandcolour 2 vernaderen.
<img src="https://github.com/user-attachments/assets/ef877617-4060-45b1-9fe1-fb268d9c2562" width="500px"> 

<img src="https://github.com/user-attachments/assets/993de773-acb9-49f7-9a8b-1671560d1415" width="500px"> 

### Gradient aangepast (percentages)
```
$el .x-bg-layer-upper-color{
  mix-blend-mode: Multiply;
  background: linear-gradient(to right, #005850 15%, rgba(255, 255, 255, 0) 70%);
}
```
### Button in de new section verwijderd

### Duidelijke focus state
```
a:focus, button:focus, input:focus, *[tabindex]:focus  {
  border: solid 3px #47b276;
  outline-style: none;
}
```

<img src="https://github.com/user-attachments/assets/4413cf9b-a5d5-4a86-831c-82296db69d1c" width="500px">

**Comment by Hadil66** [comment]
# Verbeteringen

### De rechterbutton heeft nu een `margin-left` van `2em`
<img src="https://github.com/user-attachments/assets/2f606cc4-e440-4b0e-b7c4-fef5f121d423" width="500px"> 

### Om het contrast te verhogen heb ik een overlay geplaatst op de image. `linear-gradient(to right, #00453e 0%, rgba(0, 87, 79, 0.15) 90.26%, rgba(0, 88, 80, 0) 100%);` Dit is hetzelfde gradient die op andere plaatsten op de site gebruikt wordt. De stijl blijft zo consistent. Het contrast tussen de navbar en achtergrond is nu ook veel groter.

<img src="https://github.com/user-attachments/assets/086266cb-6084-4697-b151-aa3b71f9869e" width="500px"> 

### Brandcolour 2 heeft een hoger contrast, dus alle tekst met brandcolour 3 zal ik naar brandcolour 2 vernaderen.
<img src="https://github.com/user-attachments/assets/ef877617-4060-45b1-9fe1-fb268d9c2562" width="500px"> 

<img src="https://github.com/user-attachments/assets/993de773-acb9-49f7-9a8b-1671560d1415" width="500px"> 

### Gradient aangepast (percentages)
```
$el .x-bg-layer-upper-color{
  mix-blend-mode: Multiply;
  background: linear-gradient(to right, #005850 15%, rgba(255, 255, 255, 0) 70%);
}
```
### Button in de new section verwijderd

### Duidelijke focus state
```
a:focus, button:focus, input:focus, *[tabindex]:focus  {
  border: solid 3px #47b276;
  outline-style: none;
}
```

<img src="https://github.com/user-attachments/assets/4413cf9b-a5d5-4a86-831c-82296db69d1c" width="500px">

**Comment by Hadil66** [comment]
##  [Bug](https://github.com/users/Hadil66/projects/15/views/3?pane=issue&itemId=104821762&issue=Hadil66%7CAccessibility%7C9#:~:text=Het%20linkje%20%27terug,dropdownmenu%3B%20service%20%26%20pooling) oplossen.

Als eerst heb ik de inspector geopend om te kijken wat de verschillen zijn als de code wel en niet werkt . Daar heb ik niet veel gezien dus heb ik de originele code erbij gepakt. 
```
/* Circle on hover effect */
$el .x-menu-layered > li.menu-item:not(.current_page_item) .x-anchor-content span:after{
/* 	transition: 0.5s; */
  transition:all 0.15s linear;
  left: -100px;
  content: " ";
  width: 10px;
  height: 10px;
  background-color: #005850;
}

$el .x-menu-layered  > li.menu-item:hover > a .x-anchor-content span:after, $el .x-menu-layered ul.sub-menu > li.menu-item:hover .x-anchor-content span:after, $el li.current_page_item .x-anchor-content span:after{
  content: " ";
  width: 10px;
  height: 10px;
  background-color: #005850;
  position: absolute;
  left: -30px;
  bottom: 5px;
  border-radius: 10em;
}

$el .x-menu-layered > li span.x-anchor-text-primary{
 	transition: 0.3s;
}
$el .x-menu-layered > li.menu-item:hover > a .x-anchor-content span.x-anchor-text-primary, $el li.current_page_item .x-anchor-content span.x-anchor-text-primary, $el .x-menu-layered ul.sub-menu > li.menu-item:hover .x-anchor-content span.x-anchor-text-primary{
  margin-left: 20px;
}
```

Om het beter te visualiseren heb ik een schets gemaakt.

<img src="https://github.com/user-attachments/assets/9db310d4-d55d-4edf-ae40-de9c95b78a47" width="500px">

```css

/* $el .x-menu-layered  > li.menu-item:hover > a .x-anchor-content span:after, $el .x-menu-layered ul.sub-menu > li.menu-item:hover .x-anchor-content span:after, $el .x-menu-layered li.current_menu_item > ul:not(.sub-menu) .x-anchor-content span:after */

/* $el .x-menu-layered  > li.menu-item:hover > a .x-anchor-content span:after, $el .x-menu-layered ul.sub-menu > li.menu-item:hover .x-anchor-content span:after, x-menu-layered ul.sub-menu > li.menu-item:hover .x-anchor-content span:after, x-menu-layered > li.menu-item:hover > a .x-anchor-content span:after, $el .x-menu-layered > li.menu-item:hover > a .x-anchor-content span.x-anchor-text-primary, .$el li.current_page_item .x-anchor-content span.x-anchor-text-primary, $el .x-menu-layered ul.sub-menu > li.menu-item:hover .x-anchor-content span.x-anchor-text-primary */

$el .x-menu-layered  > li.menu-item:hover > a .x-anchor-content span:after, $el .x-menu-layered ul.sub-menu > li.menu-item:hover .x-anchor-content span:after, x-menu-layered ul.sub-menu > li.menu-item:hover .x-anchor-content span:after, x-menu-layered > li.menu-item:hover > a .x-anchor-content span:after, $el .x-menu-layered > li.menu-item:hover > a .x-anchor-content span.x-anchor-text-primary, .$el li.current_page_item .x-anchor-content span.x-anchor-text-primary, $el .x-menu-layered ul.sub-menu > li.menu-item:hover .x-anchor-content span.x-anchor-text-primary $el .x-menu-layered > li.menu-item:hover > a .x-anchor-content span:after, $el .x-menu-layered ul.sub-menu > li.menu-item:hover .x-anchor-content span:after, $el li.current_page_item:not(.sub-menu li .menu-item) .x-anchor-content span:after
{
  content: " ";
  width: 10px;
  height: 10px;
  background-color: #005850;
  position: absolute;
  left: -30px;
  bottom: 5px;
  border-radius: 10em;
}
```

Ik heb er weer naar gekeken en na het maken van nog een schets kreeg ik een beetje het idee van welk item welke classes hadden.

<img src="https://github.com/user-attachments/assets/55811dec-27f5-459a-abed-44d20b9f3034" width="500px">

Ook heb ik de onnodige selecrtors verwijderd en ik kwam uit op dit:
```css
$el .x-menu-layered  > li.menu-item:hover > a .x-anchor-content span:after,
$el .x-menu-layered ul.sub-menu > li.menu-item:hover .x-anchor-content span:after, 
$el .x-menu-layered > li.menu-item:hover > a .x-anchor-content span:after, 
$el .x-menu-layered ul.sub-menu > li.menu-item:hover .x-anchor-content span:after,
$el .current-menu-item:not(:has(> .sub-menu)) .x-anchor-content span:after
{
  content: " ";
  width: 10px;
  height: 10px;
  background-color: #005850;
  position: absolute;
  left: -30px;
  bottom: 5px;
  border-radius: 10em;
}
```

Nu werkt de laatste selector niet en krijg ik het bolletje alleen bij de hover te zien en niet bij de active state. Samen met Shiu Lan heb ik er naar gekeken en we zijn helemaal vanaf het begin begonnen. 
```css
$el li:has(.current_page_item) {
  background-color: green !important;
}

$el ul.x-current-layer {
  background-color: #fff;
} 
```
 Ik heb zo een beter beeld gekregen over wat ik moet aanpassen
```css
$el .x-menu-layered > li.menu-item:hover > a .x-anchor-content span:after, 
$el .x-menu-layered ul.sub-menu > li.menu-item:hover span:after,
$el li .current_page_item span:after,
$el .x-menu-layered > li.current_page_item > a .x-anchor-content span:after
{
  content: " ";
  width: 10px;
  height: 10px;
  background-color: #005850;
  position: absolute;
  left: -30px;
  bottom: 5px;
  border-radius: 10em;  
}
```

Dit werkt nu en je ziet de bolletjes niet bij het submenu als de hoofd menu item active is.
